// generated by tools/export_sprites.py - do not edit by hand
// regenerate with: python tools/export_sprites.py
#pragma once
#include "theme.h"

// ColourKey is hand-written in theme.h; these pin it to COLOUR_KEYS.
static_assert(C_BG == 0, "ColourKey order");
static_assert(C_PANEL == 1, "ColourKey order");
static_assert(C_PANEL_HI == 2, "ColourKey order");
static_assert(C_LINE == 3, "ColourKey order");
static_assert(C_TEXT == 4, "ColourKey order");
static_assert(C_DIM == 5, "ColourKey order");
static_assert(C_LIVE == 6, "ColourKey order");
static_assert(C_WARN == 7, "ColourKey order");
static_assert(C_ROAD == 8, "ColourKey order");
static_assert(C_RAIL == 9, "ColourKey order");
static_assert(C_WINDOW == 10, "ColourKey order");
static_assert(C_DARK == 11, "ColourKey order");
static_assert(COLOUR_COUNT == 12, "ColourKey count");

// Same order as the THEME_* indices in src/sprites.h.
static const Theme THEME_DATA[] = {
    {
        "transit",
        {{12, 16, 24}, {22, 29, 42}, {32, 42, 60}, {44, 57, 78}, {233, 238, 245}, {128, 143, 165}, {120, 220, 130}, {245, 176, 66}, {38, 44, 55}, {58, 50, 44}, {214, 242, 255}, {20, 24, 30}},
        {0, 168, 224}, {151, 201, 61},
        {{ROLE_UNUSED, {0, 0, 0}}, {ROLE_IS_BODY, {0, 0, 0}}, {ROLE_IS_BRIGHT, {0, 0, 0}}, {ROLE_IS_SHADE, {0, 0, 0}}, {ROLE_IS_SHADE, {0, 0, 0}}, {ROLE_FIXED, {214, 242, 255}}, {ROLE_FIXED, {255, 255, 255}}, {ROLE_FIXED, {10, 20, 30}}, {ROLE_FIXED, {16, 26, 36}}, {ROLE_FIXED, {250, 200, 70}}, {ROLE_FIXED, {0, 140, 190}}},
        true, SCENERY_TRANSIT,
    },
    {
        "ghibli",
        {{14, 12, 34}, {26, 22, 50}, {36, 31, 64}, {54, 46, 86}, {250, 240, 220}, {168, 156, 190}, {150, 210, 140}, {255, 190, 90}, {44, 36, 60}, {52, 40, 52}, {255, 248, 226}, {24, 18, 34}},
        {232, 168, 74}, {150, 178, 226},
        {{ROLE_UNUSED, {0, 0, 0}}, {ROLE_IS_BODY, {0, 0, 0}}, {ROLE_IS_BRIGHT, {0, 0, 0}}, {ROLE_IS_SHADE, {0, 0, 0}}, {ROLE_IS_SHADE, {0, 0, 0}}, {ROLE_FIXED, {255, 248, 226}}, {ROLE_FIXED, {255, 255, 255}}, {ROLE_FIXED, {28, 18, 30}}, {ROLE_FIXED, {36, 22, 34}}, {ROLE_FIXED, {255, 210, 120}}, {ROLE_FIXED, {196, 132, 60}}},
        false, SCENERY_GHIBLI,
    },
};
#define THEME_DATA_COUNT 2
