#!/usr/bin/env python3
"""Export the Python sprites as 4bpp indexed C arrays.

Indexed rather than RGB565 so the firmware can recolour a sprite to the
route's own colour at draw time, and because 34x14 at 4bpp is 238 bytes
against 952.

    python tools/export_sprites.py     # writes src/sprites.h
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tools.board import sprites  # noqa: E402

ROLE_INDEX = {".": 0, "B": 1, "S": 2, "W": 3, "D": 4, "L": 5}

ROLE_CONST = {
    ".": "ROLE_NONE", "B": "ROLE_BODY", "S": "ROLE_SHADE",
    "W": "ROLE_WINDOW", "D": "ROLE_DARK", "L": "ROLE_LIGHT",
}

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "src", "sprites.h")


def pack(sprite):
    """4bpp, two pixels per byte, high nibble is the left pixel."""
    out = bytearray()
    for row in sprite.rows:
        for x in range(0, sprite.width, 2):
            hi = ROLE_INDEX[row[x]]
            lo = ROLE_INDEX[row[x + 1]] if x + 1 < sprite.width else 0
            out.append((hi << 4) | lo)
    return bytes(out)


def _array(name, data, per_line=12):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + per_line])
        lines.append("    " + chunk + ",")
    body = "\n".join(lines)
    return f"static const uint8_t {name}[{len(data)}] = {{\n{body}\n}};"


def render_header():
    parts = [
        "// generated by tools/export_sprites.py - do not edit by hand",
        "// regenerate after changing tools/board/sprites.py",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "// 4bpp indexed. Two pixels per byte, high nibble leftmost.",
        "// Index 0 is transparent; the rest are roles the UI maps to colours,",
        "// which is what lets one sprite render in any route's colour.",
    ]
    for letter, const in ROLE_CONST.items():
        parts.append(f"#define {const} {ROLE_INDEX[letter]}")
    parts.append("")
    parts.append(f"#define SPRITE_H {sprites.SPRITES['bus'].height}")

    for name in ("bus", "train"):
        s = sprites.SPRITES[name]
        up = name.upper()
        parts += [
            "",
            f"#define SPRITE_{up}_W {s.width}",
            f"#define SPRITE_{up}_STRIDE {(s.width + 1) // 2}",
            _array(f"SPRITE_{up}_DATA", pack(s)),
        ]
    return "\n".join(parts) + "\n"


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_header())
    print("wrote", os.path.normpath(OUT), f"({os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    main()
