#!/usr/bin/env python3
"""Export the Python sprites as 4bpp indexed C arrays.

Indexed rather than RGB565 so the firmware can recolour a sprite to the
route's own colour at draw time, and because 36x16 at 4bpp is 288 bytes
against 1152.

    python tools/export_sprites.py     # writes src/sprites.h
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tools.board import themes  # noqa: E402

ROLE_INDEX = {".": 0, "B": 1, "H": 2, "S": 3, "M": 4, "W": 5,
              "G": 6, "D": 7, "K": 8, "L": 9, "A": 10}

ROLE_CONST = {".": "ROLE_NONE", "B": "ROLE_BODY", "H": "ROLE_HIGHLIGHT",
              "S": "ROLE_SHADE", "M": "ROLE_MIDSHADOW", "W": "ROLE_WINDOW",
              "G": "ROLE_GLINT", "D": "ROLE_OUTLINE", "K": "ROLE_DETAIL",
              "L": "ROLE_LAMP", "A": "ROLE_ACCENT"}

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "src", "sprites.h")


def pack(sprite):
    """4bpp, two pixels per byte, high nibble is the left pixel."""
    out = bytearray()
    for row in sprite.rows:
        for x in range(0, sprite.width, 2):
            hi = ROLE_INDEX[row[x]]
            lo = ROLE_INDEX[row[x + 1]] if x + 1 < sprite.width else 0
            out.append((hi << 4) | lo)
    return bytes(out)


def _array(name, data, per_line=12):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + per_line])
        lines.append("    " + chunk + ",")
    body = "\n".join(lines)
    return f"static const uint8_t {name}[{len(data)}] = {{\n{body}\n}};"


def render_header():
    parts = [
        "// generated by tools/export_sprites.py - do not edit by hand",
        "// regenerate after running tools/author_art.py",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "// 4bpp indexed. Two pixels per byte, high nibble leftmost.",
        "// Index 0 is transparent; the rest are roles the UI maps to colours,",
        "// which is what lets one sprite render in any route's colour.",
    ]
    for letter, const in ROLE_CONST.items():
        parts.append(f"#define {const} {ROLE_INDEX[letter]}")

    names = themes.names()
    parts += ["", f"#define THEME_COUNT {len(names)}"]
    for i, n in enumerate(names):
        parts.append(f"#define THEME_{n.upper()} {i}")

    for n in names:
        th = themes.get(n)
        for size in ("large", "compact"):
            for kind in ("bus", "train"):
                s = th.sprite(size, kind)
                tag = f"{n.upper()}_{size.upper()}_{kind.upper()}"
                parts += [
                    "",
                    f"#define SPRITE_{tag}_W {s.width}",
                    f"#define SPRITE_{tag}_H {s.height}",
                    f"#define SPRITE_{tag}_STRIDE {(s.width + 1) // 2}",
                    _array(f"SPRITE_{tag}_DATA", pack(s)),
                ]
    return "\n".join(parts) + "\n"


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_header())
    print("wrote", os.path.normpath(OUT), f"({os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    main()
