#!/usr/bin/env python3
"""Export the Python sprites as 4bpp indexed C arrays.

Indexed rather than RGB565 so the firmware can recolour a sprite to the
route's own colour at draw time, and because 36x16 at 4bpp is 288 bytes
against 1152.

    python tools/export_sprites.py     # writes src/sprites.h, lib/core/src/theme_data.h,
                                        # lib/core/src/scenes_data.h
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tools.board import scenes, themes  # noqa: E402

ROLE_INDEX = {".": 0, "B": 1, "H": 2, "S": 3, "M": 4, "W": 5,
              "G": 6, "D": 7, "K": 8, "L": 9, "A": 10}

ROLE_CONST = {".": "ROLE_NONE", "B": "ROLE_BODY", "H": "ROLE_HIGHLIGHT",
              "S": "ROLE_SHADE", "M": "ROLE_MIDSHADOW", "W": "ROLE_WINDOW",
              "G": "ROLE_GLINT", "D": "ROLE_OUTLINE", "K": "ROLE_DETAIL",
              "L": "ROLE_LAMP", "A": "ROLE_ACCENT"}

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "sprites.h")
CORE = os.path.join(ROOT, "lib", "core", "src")
THEME_OUT = os.path.join(CORE, "theme_data.h")
SCENES_OUT = os.path.join(CORE, "scenes_data.h")

KIND_CONST = {"bus": "Kind::Bus", "train": "Kind::Train"}
MAX_DEPARTURES = 4  # lib/core/src/model.h

# Order of the C enum ColourKey in lib/core/src/theme.h.
COLOUR_KEYS = ["bg", "panel", "panel_hi", "line", "text", "dim", "live",
               "warn", "road", "rail", "window", "dark"]

SCENERY_CONST = {None: "SCENERY_NONE", "transit": "SCENERY_TRANSIT",
                 "ghibli": "SCENERY_GHIBLI"}

GENERATED_BANNER = [
    "// generated by tools/export_sprites.py - do not edit by hand",
    "// regenerate with: python tools/export_sprites.py",
]


def pack(sprite):
    """4bpp, two pixels per byte, high nibble is the left pixel."""
    out = bytearray()
    for row in sprite.rows:
        for x in range(0, sprite.width, 2):
            hi = ROLE_INDEX[row[x]]
            lo = ROLE_INDEX[row[x + 1]] if x + 1 < sprite.width else 0
            out.append((hi << 4) | lo)
    return bytes(out)


def _array(name, data, per_line=12):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + per_line])
        lines.append("    " + chunk + ",")
    body = "\n".join(lines)
    return f"static const uint8_t {name}[{len(data)}] = {{\n{body}\n}};"


def render_header():
    parts = [
        "// generated by tools/export_sprites.py - do not edit by hand",
        "// regenerate after running tools/author_art.py",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "// 4bpp indexed. Two pixels per byte, high nibble leftmost.",
        "// Index 0 is transparent; the rest are roles the UI maps to colours,",
        "// which is what lets one sprite render in any route's colour.",
    ]
    for letter, const in ROLE_CONST.items():
        parts.append(f"#define {const} {ROLE_INDEX[letter]}")

    names = themes.names()
    parts += ["", f"#define THEME_COUNT {len(names)}"]
    for i, n in enumerate(names):
        parts.append(f"#define THEME_{n.upper()} {i}")

    for n in names:
        th = themes.get(n)
        for size in ("large", "compact"):
            for kind in ("bus", "train"):
                s = th.sprite(size, kind)
                tag = f"{n.upper()}_{size.upper()}_{kind.upper()}"
                parts += [
                    "",
                    f"#define SPRITE_{tag}_W {s.width}",
                    f"#define SPRITE_{tag}_H {s.height}",
                    f"#define SPRITE_{tag}_STRIDE {(s.width + 1) // 2}",
                    _array(f"SPRITE_{tag}_DATA", pack(s)),
                ]
    return "\n".join(parts) + "\n"


def _rgb(c):
    return "{%d, %d, %d}" % tuple(c)


def _role_spec(value):
    if value == "body":
        return "{ROLE_IS_BODY, {0, 0, 0}}"
    if value == "shade":
        return "{ROLE_IS_SHADE, {0, 0, 0}}"
    if value == "bright":
        return "{ROLE_IS_BRIGHT, {0, 0, 0}}"
    return "{ROLE_FIXED, %s}" % _rgb(value)


def render_theme_header():
    parts = GENERATED_BANNER + [
        "#pragma once",
        '#include "theme.h"',
        "",
        "// ColourKey is hand-written in theme.h; these pin it to COLOUR_KEYS.",
    ]
    for i, key in enumerate(COLOUR_KEYS):
        parts.append(f'static_assert(C_{key.upper()} == {i}, "ColourKey order");')
    parts += [f'static_assert(COLOUR_COUNT == {len(COLOUR_KEYS)}, "ColourKey count");',
              "",
              "// Same order as the THEME_* indices in src/sprites.h.",
              "static const Theme THEME_DATA[] = {"]
    names = themes.names()
    for name in names:
        th = themes.get(name)
        if set(th.colours) != set(COLOUR_KEYS):
            raise ValueError(f"theme {name!r} colours differ from COLOUR_KEYS")
        roles = ["{ROLE_UNUSED, {0, 0, 0}}"] * len(ROLE_INDEX)
        roles[ROLE_INDEX["B"]] = "{ROLE_IS_BODY, {0, 0, 0}}"
        for letter, value in th.roles.items():
            roles[ROLE_INDEX[letter]] = _role_spec(value)
        scenery = SCENERY_CONST[th.scenery.__name__ if th.scenery else None]
        colours = ", ".join(_rgb(th.colour(k)) for k in COLOUR_KEYS)
        parts += [
            "    {",
            f'        "{name}",',
            f"        {{{colours}}},",
            f"        {_rgb(th.kind_fallback['bus'])}, {_rgb(th.kind_fallback['train'])},",
            f"        {{{', '.join(roles)}}},",
            f"        {'true' if th.use_route_color else 'false'}, {scenery},",
            "    },",
        ]
    parts += ["};", f"#define THEME_DATA_COUNT {len(names)}"]
    return "\n".join(parts) + "\n"


def _cstr(s):
    """A C string literal, or nullptr. ASCII only: the panel font is GLCD."""
    if s is None:
        return "nullptr"
    if not s.isascii():
        raise ValueError(f"the panel font cannot draw non-ASCII text: {s!r}")
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _bool(b):
    return "true" if b else "false"


def render_scenes_header():
    parts = GENERATED_BANNER + [
        "#pragma once",
        '#include "demo.h"',
        "",
        "// tools/board/scenes.py, in order. DEMO_MODE plays these.",
        "static const Scene SCENE_DATA[] = {",
    ]
    for name, board in scenes.SCENES.items():
        parts.append(f"    {{{_cstr(name)}, {_cstr(board.clock)}, {_cstr(board.location)}, "
                     f"{board.stale_s}, {_bool(board.dimmed)}, {len(board.watches)}, {{")
        for w in board.watches:
            if len(w.departures) > MAX_DEPARTURES:
                raise ValueError(f"scene {name!r}: more than {MAX_DEPARTURES} departures")
            deps = ", ".join(f"{{{d.eta_s}, {_bool(d.live)}, {_bool(d.cancelled)}}}"
                             for d in w.departures)
            parts.append(f"        {{{_cstr(w.badge)}, {_cstr(w.headsign)}, "
                         f"{KIND_CONST[w.kind]}, {_cstr(w.route_color)}, {_cstr(w.message)}, "
                         f"{len(w.departures)}, {{{deps}}}}},")
        parts.append("    }},")
    parts += ["};", f"#define SCENE_DATA_COUNT {len(scenes.SCENES)}"]
    return "\n".join(parts) + "\n"


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote", os.path.normpath(path), f"({os.path.getsize(path)} bytes)")


def main():
    _write(OUT, render_header())
    _write(THEME_OUT, render_theme_header())
    _write(SCENES_OUT, render_scenes_header())


if __name__ == "__main__":
    main()
